from llm_agent.ollma_chat import get_llm_response


des="""

### Filter-Calculator
This code visualizes a 3D plane colored by a mathematical function, using `vtkCalculator` for scalar values and `vtkMapper` for coloring.

---

### Filter-ContourTriangulator
Generates a closed circular polyline from 16 points and triangulates it using `vtkContourTriangulator` for wireframe rendering.

---

### Filter-ImageLabelOutline
Displays a 2D image volume with an outlined labelmap. Specific regions (high/low values) are highlighted in red/green with transparent outlines.

---

### Filter-ImageMarchingCubes
Visualizes a 3D sphere by generating a scalar field with `vtkSampleFunction` and extracting an isosurface using `vtkImageMarchingCubes`.

---

### Filter-ImageMarchingSquares
Creates a 3D visualization by sampling an implicit boolean function and extracting contour lines with `vtkImageMarchingSquares`.

---

### Filter-ImageSlice
Generates and displays a 2D random image (100x100) using `vtkImageSlice` and `vtkImageMapper`.

---

### Filter-ImageStreamline
Visualizes a 3D vector field using `vtkImageStreamline` for streamlines, `vtkOutlineFilter` for data bounds, and seed points, with interactive resolution controls.

---

### Filter-MultiImageSlice
Loads a 3D volume and displays three orthogonal image slices (I, J, K planes) at the 30th layer using `vtkHttpDataSetReader` and `vtkImageSlice`.

---

### Filter-TriangleFilter
Visualizes a 3D cylinder generated by `vtkCylinderSource`, ensuring triangular geometry with `vtkTriangleFilter` for wireframe rendering.

---

### Filter-VolumeClip
Renders a 3D medical volume (`headsq.vti`) with a clipping plane, using `vtkVolumeMapper` and `vtkVolumeActor` for customized appearance.

---

### Filter-VolumeContour
Loads a 3D volumetric dataset (`headsq.vti`) and extracts an isosurface using `vtkImageMarchingCubes`, with a real-time adjustable iso-value.

---

### IO-ElevationReader
Loads and visualizes 3D elevation data from a CSV, applying a texture image, using `vtkElevationReader` and `vtkMapper`.

---

### IO-GCodeReader
Loads and visualizes a G-code file as 3D colored line segments per layer using `vtkGCodeReader`.

---

### IO-HttpdatasetReader
Loads and visualizes a 3D model (VTP format) from a remote URL using `vtkHttpDataSetReader` with gzip support.

---

### IO-OBJReader
Loads and renders a 3D OBJ model with its associated MTL materials using `vtkOBJReader` and `vtkMTLReader`, allowing mesh part visibility toggling.

---

### IO-PDBReader
Loads a PDB file (caffeine molecule) and visualizes it with `vtkPDBReader` and `vtkMoleculeToRepresentation`, showing atoms as spheres and bonds as sticks.

---

### IO-PolyDataReader
Loads and visualizes a 3D polygonal data file (`test_cone.vtp`) using `vtkXMLPolyDataReader` and `vtkMapper`.

---

### IO-Screenshot
Renders a 3D sphere and captures the canvas as a PNG image (`IO-Screenshot.png`).

---

### IO-StickMapper
Generates a plane and uses `vtkCalculator` to create custom point data ('orientation', 'temperature', 'pressure'), which `vtkStickMapper` could use for rendering (currently not fully connected).

---

### IO-XMLImageDataWriter
Loads 3D volume data, writes it to a binary XML format using `vtkXMLImageDataWriter`, reads it back with `vtkXMLImageDataReader`, and visualizes it.

---

### IO-XMLImagePolyDataWriter
Loads 3D polydata, writes it to a string using `vtkXMLPolyDataWriter`, reads it back with `vtkXMLPolyDataReader`, and renders it, allowing download of the generated VTP file.

---

### Rendering-GlyphMapper
Visualizes a 3D plane with glyphs (e.g., cones) whose scale and orientation are based on scalar and vector data, using `vtkGlyph3DMapper` and `vtkCalculator`.

---

### Rendering-Image2D
Displays a synthetic 2D image generated by `vtkRTAnalyticSource` using `vtkImageMapper` and `vtkImageSlice`.

---

### Rendering-ItkWasmVolume
Loads a medical image dataset (MHA) and renders it as a 3D volume using `vtkVolumeMapper` with custom color and opacity transfer functions.

---

### Rendering-ManyRenderers
Displays multiple interactive 3D objects (cone, sphere, cube, cylinder) in separate, independently styled renderers with animation and layout adjustments.

---

### Rendering-MultiSliceImageMapper
Loads a 3D volume (`headsq.vti`) and displays three orthogonal slices (I, J, K) with interactive controls for position and color properties.

---

### Rendering-SphereMapper
Visualizes a 3D sphere generated by `vtkSphereSource` and rendered with `vtkSphereMapper`.

---

### Rendering-StickMapper
Creates a 3D visualization where a plane is rendered using a `vtkStickMapper`. The plane's geometry is generated with a `vtkPlaneSource`, and `vtkCalculator` processes the data to generate custom point attributes ('orientation', 'temperature', 'pressure') which `vtkStickMapper` uses to control the orientation and scaling of the sticks. The visualization is displayed in a full-screen renderer with a dark background. Additionally, UI controls allow adjusting the X and Y resolution of the plane, which dynamically updates the visualization.

---

### Rendering-VolumeMapper
Loads a 3D volume dataset and renders it using `vtkVolumeActor` and `vtkVolumeMapper` with extensive customization for appearance and quality.

"""
def slipt_query(query):
    system="""
     You are a professional VTK.js visualization assistant. Please break down the user's visualization query into clear, actionable steps.

        Example format:
        Original query: [Generate HTML with vtk.js to visualize sliced rotor data

        Load data:
        - Load from http://127.0.0.1:5000/dataset/rotor.vti

        Processing:
        - Slice ：Set as active scalar "Pressure"
        - Applies a Y-axis slice at 80% /depth (setSlice, setSlicingMode).
        Visualization:
        - Maps pressure values to colors (blue→white→red gradient) and opacity (full opacity).
        - UI: Adds an orientation marker (XYZ axes) for spatial reference.
        6. No GUI controls required]

        Step breakdown:
       querys = [
        {"description": "Introduce necessary VTK.js modules via the CDN link: https://unpkg.com/vtk.js;"},
        {"description": "Data Loading — Load the VTK dataset from http://127.0.0.1:5000/dataset/rotor.vti using vtkXMLImageDataReader;"},
        {"description": "Data Processing — Set 'Pressure' as the active scalar and apply a slice at 80% /depth along the Y-axis using vtkImageSlice;"},
        {"description": "Visualization Setup — Map pressure values to a blue→white→red color gradient and set full opacity using vtkColorTransferFunction, vtkPiecewiseFunction, vtkMapper;"},
        {"description": "Add UI Element — Integrate an XYZ axes orientation marker for spatial reference using vtkOrientationMarkerWidget, vtkAxesActor;"},
        {"description": "Integrate all components and render the visualization without GUI controls using vtkRenderWindow, vtkRenderer,vtkActor;"}
    ]
        Please break down the following query using the above format
    """


    # query=
    model_name="qwen3-plus"
    return get_llm_response(query, model_name, system)

def main(query):

    system="""
You are a query assistant. Your task is to find the most relevant information from the provided "Content Library" ONLY. Do NOT use any external knowledge. Return only the top 6 most relevant results(title + content), without any additional text or explanation.
"""
    Q=f"""From the provided content library, please find the top 6 most relevant pieces of information for the current query. Return only the results, one per line.
Query: {query}
Content Library: {des}
"""


    model_name="qwen3-plus"
    r=get_llm_response(Q, model_name, system)
    print(r)
    return r


if __name__ == "__main__":

    queries=[
"""
 Generate HTML with vtk.js to visualize sliced rotor data

        Load data:
        - Load from http://127.0.0.1:5000/dataset/rotor.vti

        Processing:
        - Slice ：Set as active scalar "Pressure"
        - Applies a Y-axis slice at 80% /depth (setSlice, setSlicingMode).
        Visualization:
        - Maps pressure values to colors (blue→white→red gradient) and opacity (full opacity).
        - UI: Adds an orientation marker (XYZ axes) for spatial reference.
        6. No GUI controls required
""",
"""
 Rotor Isosurface Visualization Requirements:
        - Data: Load from rotor_simplified.vti dataset
        - Process: Calculate velocity magnitude from vector components (√(vx²+vy²+vz²))
        - Features:
        * Isosurface extraction using Marching Cubes algorithm
        * Rainbow colormap (blue->cyan->white->orange->red)
        * Surface rendering with ambient(0.3), diffuse(0.7), specular(0.4) lighting
        * Interactive 3D view with orientation axes widget
        - Implementation: vtk.js framework with responsiv
""",
"""
Create vtk.js visualization for isabel.vti dataset with velocity field.

        Load data from: http://127.0.0.1:5000/dataset/isabel.vti

        Generate streamlines from center seeds, show outline.

        Use vtkFullScreenRenderWindow and load vtk.js from CDN.
        
""",
"""
 Generate HTML with vtk.js to visualize volume rendering

        Load from http://127.0.0.1:5000/dataset/airfoil_oneslice.vtp
        Scalar Mapping:
        Activates the p scalar array for color encoding
        Visualization:
        Renders the colors and representation
        positions the camera to focus on the dataset bounds
        
""",


    ]
    splited_queries=[
        [
        {"description": "Introduce necessary VTK.js modules via the CDN link: https://unpkg.com/vtk.js"},
        {"description": "Data Loading — Load the VTK dataset from http://127.0.0.1:5000/dataset/rotor.vti"},
        {"description": "Data Processing — Set 'Pressure' as the active scalar and apply a slice at 80% /depth along the Y-axis"},
        {"description": "Visualization Setup — Map pressure values to a blue→white→red color gradient and set full opacity"},
        {"description": "Add UI Element — Integrate an XYZ axes orientation marker for spatial reference"},
        {"description": "Integrate all components and render the visualization without GUI controls"}
        ],
        [ 
            {
                "description": "Data Loading — Load the rotor_simplified.vti dataset using VTK.js data reader functions"
            },
            {
                "description": "Data Processing — Calculate the velocity magnitude from vector components (vx, vy, vz) using vtkImageMagnitude or similar VTK.js functionality to derive √(vx²+vy²+vz²)"   
            },
            {
                "description": "Feature Extraction — Apply the Marching Cubes algorithm to extract isosurfaces from the processed velocity magnitude data"
            },
            {
                "description": "Visualization Setup — Map the extracted isosurface values to a rainbow colormap (blue→cyan→white→orange→red) and configure surface rendering with lighting parameters: ambient(0.3), diffuse(0.7), specular(0.4)"
            },
            {
                "description": "Add UI Element — Integrate an interactive 3D view with an orientation axes widget for spatial reference"  
            },
            {
                "description": "Responsive UI Implementation — Ensure the visualization is responsive and integrates seamlessly within the web application framework using vtk.js"
            }
    ],
    [
            {"description": "Introduce necessary VTK.js modules via the CDN link: https://unpkg.com/vtk.js"},
            {"description": "Data Loading — Load the VTK dataset from http://127.0.0.1:5000/dataset/isabel.vti"},
            {"description": "Data Processing — Set 'velocity' as the active vector field for streamline generation"},
            {"description": "Streamline Setup — Generate streamlines starting from center seeds within the dataset"},
            {"description": "Outline Visualization — Add an outline representation of the dataset to provide spatial context"},       
            {"description": "Rendering Configuration — Use vtkFullScreenRenderWindow to handle the rendering setup and display the visualization in full screen"},
            {"description": "Integrate all components and render the visualization including streamlines and outline without additional GUI controls"}
        ],
    [
            {"description": "Introduce necessary VTK.js modules via the CDN link: https://unpkg.com/vtk.js"},
            {"description": "Data Loading — Load the VTK dataset from http://127.0.0.1:5000/dataset/airfoil_oneslice.vtp"},
            {"description": "Scalar Mapping — Activate the 'p' scalar array for color encoding in the visualization"},
            {"description": "Visualization Setup — Configure volume rendering to display colors and representations based on the 'p' scalar values"},
            {"description": "Camera Positioning — Adjust the camera position to focus on the dataset bounds ensuring all data is clearly visible"},
            {"description": "Integrate all components and render the visualization"}
        ]
        
        ]

if __name__ == "__main__":
    for query in queries:
        # r = slipt_query(query)
        r=main(query)
        with open("output.txt", "a", encoding='utf-8') as f:
            f.write(f"Query: {query}\n")
            f.write(f"Result: {r}\n\n")

    


   
